---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
values <- list(data = list())
for(item in table_names){
 df <- sbtab_tables_list[[item]]
    values$data[[item]] <- df
}

output <- list("data")

=======
for(n in 1:12){
  print(table_names[n])
}
table_names[1]
>>>>>>> 6b16831 (created function for reading sbtab files)
=======
# open tabs included in sbtab in the dashboard
sbtabfile <-  suppressWarnings(read_sbtab("liver_bile_example/liver_bile_template.tsv"))
table <- "Compartment"
empty_tabs <- as.list(table_names)
current_tabs <- list()
nrs <- c(1, 3, 3, 5)
<<<<<<< HEAD

names(sbtabfile[[table]][which(sbtabfile[[table]][1,] != "")])
names(sbtab_tables_list[[table]][nrs])

<<<<<<< HEAD
for(table in names(sbtabfile)){
  headers <- append(headers,
                    paste0('!!SBtab TableID="t_', table, '"', ' SBtabVersion="', "input$sbtab_version", '"',' Document="', "input$set_documentname", '"',' TableType="', table, '"',' TableName="', table, '"')
        )
}
headernames <- vector()
for(header in 1:length(headers)){
  headernames <- append(headernames, table_names[which(table_names == str_extract(headers[header], table_names))])
}
names(headers) <- headernames
names(sbtabfile)[2]
for(table in names(sbtabfile)){
empty_tabs <- empty_tabs[empty_tabs!=table]
}
>>>>>>> 48dc8b5 (Uploading TSV files works and opens the corresponding tabs in the app)
=======
>>>>>>> 1025e35 (open columns get updated on file upload)
=======

names(sbtabfile[[table]][which(sbtabfile[[table]][1,] != "")])
names(sbtab_tables_list[[table]][nrs])

>>>>>>> d864e55 (open columns get updated on file upload)
=======
test <- read_sbtab(sbml_file)
colnames(test[[2]])
gsub("(^|[[:space:]])([[:alpha:]])", "\\1\\U\\2",    # Uppercase with Base R
     colnames(test[[2]]),
     perl = TRUE)
str_to_upper(colnames(test[[2]]))
colnames(test[["Compound"]])[7] <- "HasOnlySubstanceUnits"
sbtab <- sbtab_tables_list
x <- names(test)[1]
sbtab[names(test)] <- lapply(names(test), function(name){
sbtab[[name]] <- add_row(sbtab[[name]], test[[name]], .after = 0)
})
sbtab[["Compound"]] <- add_row(sbtab[["Compound"]], test[["Compound"]], .after = 0)
test[["Reaction"]][]
>>>>>>> 07ca341 (SBML uploading functional)
```

